Adds OSS dm and removes fixed versions
qub-it/fenixedu-ulisboa-tools pull request #3
Opened 2023-12-06 11:35 UTC by joaofreitas-qubit

Relates with: #qubIT-Omnis-4736

2023-12-11 17:53 UTC, joaojtmarques-qubit requested changes
Remove repositories and distributionManagement tags

2023-12-12 12:39 UTC, pabrantes commented
> Remove repositories and distributionManagement tags

The distribution management he cannot remove because it's different from the parent. But the repositories are present in the parent and can be removed. And although fenixedu-maven-repository is not directly defined in the parent pom, our repository is defined that mirrors that one as well.

2023-12-12 12:40 UTC, pabrantes requested changes
Remove repositories definition (keep distributionManagement though)

2023-12-13 09:54 UTC, pabrantes approved these changes

2023-12-13 16:25 UTC, joaojtmarques-qubit approved these changes

2023-12-13 16:25 UTC, merged